[package]
name = "bevy_xcap"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.17", default-features = false, features = ["bevy_window", "bevy_log"] }
xcap = "0.8"
image = "0.25"
raw-window-handle = "0.6"
